apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: nodeport
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: nodeport
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: app
    spec:
      {{- if gt (int (default 1 .Values.replicaCount)) 1}}
      # Spread pods across nodes if running multiple replicas
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: io.kompose.service
                      operator: In
                      values:
                        - app
                topologyKey: kubernetes.io/hostname
      {{- end}}
      containers:
        - env:
            - name: DB_HOST
              value: mariadb
            - name: DB_NAME
              value: ZillowHomeValueForecast
            - name: DB_PASSWORD
              value: password
            - name: DB_USER
              value: user
          image: dstanecki/zhf_multi_arch:latest
          name: app
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
