apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: nodeport
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: app
    environment: {{ .Values.environment }}
  name: {{ if eq .Values.environment "prod" }}app-prod{{ else }}app-dev{{ end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: app
      environment: {{ .Values.environment }}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: nodeport
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: app
        environment: {{ .Values.environment }}
    spec:
      # Spread pods across nodes if running multiple replicas
      {{- if gt (int (default 1 .Values.replicaCount)) 1}}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: io.kompose.service
                      operator: In
                      values:
                        - app
                topologyKey: kubernetes.io/hostname
      {{- end}}
      containers:
        - env:
            - name: DB_HOST
              value: {{ if eq .Values.environment "prod" }}mariadb-prod{{ else }}mariadb-dev{{ end }}
            - name: DB_NAME
              value: ZillowHomeValueForecast
            - name: DB_PASSWORD
              value: password
            - name: DB_USER
              value: root
          image: "{{ .Values.appImage.repository }}:{{ .Values.appImage.tag }}"
          name: app
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
