apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mariadb
  name: {{ if eq .Values.environment "prod" }}mariadb-prod{{ else }}mariadb-dev{{ end }}
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: mariadb
