apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mariadb
  name: {{ if eq .Values.environment "prod" }}mariadb-prod{{ else }}mariadb-dev{{ end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mariadb
    spec:
      # Spread pods across nodes if running multiple replicas
      {{- if gt (int (default 1 .Values.replicaCount)) 1}}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: io.kompose.service
                    operator: In
                    values:
                      - mariadb
              topologyKey: kubernetes.io/hostname
      {{- end}}
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: ZillowHomeValueForecast
            - name: MYSQL_ROOT_PASSWORD
              value: password
          image: "{{ .Values.dbImage.repository }}:{{ .Values.dbImage.tag }}"
          name: mariadb
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits: 
              cpu: "500m"
              memory: "1Gi"
      restartPolicy: Always
