apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ if eq .Values.environment "prod" }}zhf-prod-tls{{ else }}zhf-dev-tls{{ end }}
spec:
  secretName: {{ if eq .Values.environment "prod" }}zhf-prod-tls{{ else }}zhf-dev-tls{{ end }}
  issuerRef:
    name: {{ if eq .Values.environment "prod" }}letsencrypt-prod{{ else }}letsencrypt-dev{{ end }}
    kind: ClusterIssuer
  commonName: {{ if eq .Values.environment "prod" }}zhf.danielstanecki.com{{ else }}zhf-dev.danielstanecki.com{{ end }}
  dnsNames:
    - {{ if eq .Values.environment "prod" }}zhf.danielstanecki.com{{ else }}zhf-dev.danielstanecki.com{{ end }}
