apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 1.3.0
      helm:
        valueFiles:
          - $values/argo/apps/alloy/values.yaml
    - repoURL: https://github.com/dstanecki/zillow-housing-forecast.git
      targetRevision: HEAD
      ref: values
  syncPolicy: {}
