# Force monolithic deployment with one replica
deploymentMode: SingleBinary
singleBinary:
  replicas: 1
  # IMPORTANT: don't create a PVC; use ephemeral emptyDir instead.
  persistence:
    enabled: false

  # Mount an emptyDir at /var/loki (writable, in-cluster)
  extraVolumes:
    - name: loki-data
      emptyDir: {}            

  extraVolumeMounts:
    - name: loki-data
      mountPath: /var/loki

loki:
  auth_enabled: false
  # TSDB with local filesystem
  schemaConfig:
    configs:
      - from: "2025-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  commonConfig:
    replication_factor: 1

  # Storage backend: filesystem (in-pod)
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks

# Keep the gateway (ClusterIP) so Alloy/Grafana can talk to http://loki-gateway
gateway:
  enabled: true

chunksCache:
  enabled: false
resultsCache:
  enabled: false

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
