# Tempo single-binary (monolithic) with persistent storage
persistence:
  enabled: true
  size: 30Gi

tempo:
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        enabled: true
        dir: /var/tempo/wal

service:
  type: ClusterIP
  ports:
    otlp-grpc: 4317
    otlp-http: 4318
    jaeger-grpc: 14250
    jaeger-http: 14268
    zipkin: 9411

resources:
  limits:
    cpu: "2"
    memory: 4Gi
  requests:
    cpu: "500m"
    memory: 1Gi
