prometheus:
  service:
    type: NodePort
    nodePort: 30090

  prometheusSpec:
    nodeSelector:
      ssd: "true"
    scrapeInterval: 15s         # Default is 15s
    evaluationInterval: 30s
    retention: 5d              # Reduce retention from default 15d
    resources:
      requests:
        memory: 512Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 500m
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

grafana:
  nodeSelector:
    ssd: "true"
  service:
    type: NodePort
    nodePort: 30030
  resources:
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 200Mi
      cpu: 200m

nodeExporter:
  enabled: true

prometheus-node-exporter:
  extraArgs:
    - --web.listen-address=:9101
  containerPort: 9101
  service:
    port: 9101
    targetPort: 9101

kube-state-metrics:
  enabled: true
  nodeSelector:
    ssd: "true"

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      ssd: "true"
    replicas: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 100m

prometheusOperator:
  nodeSelector:
    ssd: "true"
