apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: dev
            valuesPath: argo/apps/redis/values-dev.yaml
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
          - env: prod
            namespace: prod
            valuesPath: argo/apps/redis/values-prod.yaml
            syncPolicy: {}
  template:
    metadata:
      name: redis-{{env}}
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      sources:
        - repoURL: https://charts.bitnami.com/bitnami
          chart: redis
          targetRevision: 21.2.12
          helm:
            valueFiles:
              - $values/{{valuesPath}}
        - repoURL: https://github.com/dstanecki/zillow-housing-forecast.git
          targetRevision: HEAD
          ref: values
      syncPolicy: {{syncPolicy}}
