apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: dev
            valuesPath: argo/apps/redis/values-dev.yaml
            autoSync: true
          - env: prod
            namespace: prod
            valuesPath: argo/apps/redis/values-prod.yaml
            autoSync: false
  template:
    metadata:
      name: redis-{{env}}
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      sources:
        - repoURL: https://charts.bitnami.com/bitnami
          chart: redis
          targetRevision: 21.2.12
          helm:
            valueFiles:
              - $values/{{valuesPath}}
        - repoURL: https://github.com/dstanecki/zillow-housing-forecast.git
          targetRevision: HEAD
          ref: values
      syncPolicy: '{{ syncPolicy }}'
  parameters:
    - name: syncPolicy
      value: |
        {{- if eq .autoSync true }}
        automated:
          prune: true
          selfHeal: true
        {{- end }}
