apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis-appset
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: redis-dev
            namespace: dev
            valueFiles:
              - argo/apps/redis/values-dev.yaml
            autoSync: true
            prune: true
          - name: redis-prod
            namespace: prod
            valueFiles:
              - argo/apps/redis/values-prod.yaml
            autoSync: false
  template:
    metadata:
      name: '{{ .name }}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      sources:
        - repoURL: https://github.com/dstanecki/zillow-housing-forecast.git
          targetRevision: HEAD
          ref: values
  templatePatch: |
    spec:
      sources:
        - repoURL: https://charts.bitnami.com/bitnami
          chart: redis
          targetRevision: 21.2.12
          helm:
            valueFiles:
            {{- range .valueFiles }}
              - $values/{{ . }}
            {{- end }}
        - repoURL: https://github.com/dstanecki/zillow-housing-forecast.git
          targetRevision: HEAD
          ref: values
    {{- if .autoSync }}
      syncPolicy:
        automated:
          prune: {{ .prune }}
          selfHeal: true
    {{- end }}
