apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-redis # DEV
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: redis
      targetRevision: 21.2.12
      helm:
        valueFiles:
          - $values/argo/apps/redis/values-dev.yaml
    - repoURL: https://github.com/dstanecki/zillow-housing-forecast.git
      targetRevision: HEAD
      ref: values
  syncPolicy: {}
