architecture: standalone

replica:
  replicaCount: 0

master:
  persistence:
    enabled: true
    size: 256Mi

metrics:
  enabled: false
  serviceMonitor:
    enabled: false
    additionalLabels: # Crucial for Prometheus to be able to discover the service monitor
      release: prometheus 

auth:
  enabled: true
  existingSecret: redis-password


redis:
  extraFlags:
    - --maxmemory 150mb
    - --maxmemory-policy allkeys-lru
