prometheus:
  service:
    type: NodePort
    nodePort: 30090

  prometheusSpec:
    scrapeInterval: 30s         # Default is 15s
    evaluationInterval: 30s
    retention: 2d              # Reduce retention from 15d to 2d
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 300m
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

grafana:
  service:
    type: NodePort
    nodePort: 30030
  resources:
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 200Mi
      cpu: 200m

# DISABLED TO SAVE RAM
nodeExporter:
  enabled: false

kubeStateMetrics:
  enabled: false

alertmanager:
  alertmanagerSpec:
    replicas: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 100m
