prometheus:
  service:
    type: NodePort
    nodePort: 30090

  prometheusSpec:
    nodeSelector:
      node-role.kubernetes.io/ssd: "true"
    scrapeInterval: 15s         # Default is 15s
    evaluationInterval: 30s
    retention: 5d              # Reduce retention from default 15d
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 300m
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

grafana:
  nodeSelector:
    node-role.kubernetes.io/ssd: "true"
  service:
    type: NodePort
    nodePort: 30030
  resources:
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 200Mi
      cpu: 200m

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      node-role.kubernetes.io/ssd: "true"
    replicas: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 100m
