apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-operator
      targetRevision: 0.97.1
      helm:
        valueFiles:
          - $values/argo/apps/opentelemetry-operator/values.yaml
    - repoURL: https://github.com/dstanecki/zillow-housing-forecast.git
      targetRevision: HEAD
      ref: values
  syncPolicy: {}
