apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd  # where the Argo CD Application controller is running
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 8.1.3
      helm:
        releaseName: argocd
        valueFiles:
          - $values/argo/apps/argocd/values.yaml
    - repoURL: https://github.com/dstanecki/zillow-housing-forecast.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
