configs:
  params:
    server.insecure: "true" # Disable ArgoCD's TLS management because Traefik is handling TLS
  rbac:
    policy.default: role:admin
    policy.csv: |
      g, admin, role:admin

server:
  service:
    type: ClusterIP
    ports:
      http: 80

# Disabling ArgoCD's built-in ingress because I'm using my own Traefik IngressRoute
  ingress:
    enabled: false

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 250m

dex:
  enabled: false

repoServer:
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m

applicationController:
  resources:
    requests:
      memory: 200Mi
      cpu: 50m
    limits:
      memory: 400Mi
      cpu: 200m
