apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: nodeport
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: nodeport
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: mariadb
            - name: DB_NAME
              value: ZillowHomeValueForecast
            - name: DB_PASSWORD
              value: password
            - name: DB_USER
              value: user
          image: dstanecki/zhf_multi_arch:latest
          name: app
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
