services:
  app:
    build: .
    image: dstanecki/zhf:latest
    ports:
      - "5000:5000"
    labels:
      - kompose.service.type=nodeport
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=ZillowHomeValueForecast
  mariadb:
    image: dstanecki/zhf-mariadb:latest
    environment:
       - MYSQL_ROOT_PASSWORD=password # Password var is required in both app and db containers
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data:
