configs:
  params:
    server.insecure: "true" # Disable ArgoCD's TLS management because Traefik is handling TLS
    controller.status.processors: "5"  # Fewer concurrent processors
    controller.operation.processors: "2"

server:
  service:
    type: ClusterIP
    ports:
      http: 80

# Disabling ArgoCD's built-in ingress because I'm using my own Traefik IngressRoute
  ingress:
    enabled: false

  resources:
    requests:
      memory: 150Mi
      cpu: 50m
    limits:
      memory: 250Mi
      cpu: 150m

dex:
  enabled: false

repoServer:
  resources:
    requests:
      memory: 150Mi
      cpu: 50m
    limits:
      memory: 250Mi
      cpu: 100m

applicationController:
  resources:
    requests:
      memory: 200Mi
      cpu: 50m
    limits:
      memory: 400Mi
      cpu: 200m
